[[fts]]
arch = "aarch64"
git-tree-sha1 = "b95c501afd1d7d6c4866f7c9538ee93870db98b5"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "f60096ef715c88fd14e60426dcc3e94305c3edeb3de0a4818d6803be4c14f563"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.8+0/fts.v1.2.8.aarch64-linux-gnu.tar.gz"
[[fts]]
arch = "aarch64"
git-tree-sha1 = "864ef14f951401f9fd556ec3618a6502d270c4f7"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "4888223298194434d92238621c8c52a8fa0eadafe9517c55a971afd5db287d7b"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.8+0/fts.v1.2.8.aarch64-linux-musl.tar.gz"
[[fts]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a9eb548e7b5a321a5beaaa7c9f2aebbd4983ef7c"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "e58739f31ea15225041874b645d07be29c0011b2394d76f01cbd390a87fbf226"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.8+0/fts.v1.2.8.armv6l-linux-gnueabihf.tar.gz"
[[fts]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0b3c33caa6adee82c139aaca512d224a22ad8f9c"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "4a91a97d525245ad27493d82d9659a518fc604e75a4f8ea18e03f7e5313149e7"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.8+0/fts.v1.2.8.armv6l-linux-musleabihf.tar.gz"
[[fts]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c5d2883f92efdca777e06b2f858dfb230bb50874"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "4e0df1b8577a52d7fafcf9e917d57dd7f5bb7fb8dde9b65bedbacfdb3537c1f4"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.8+0/fts.v1.2.8.armv7l-linux-gnueabihf.tar.gz"
[[fts]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d65f3797fd88f16102af605224cfafe9d14284b"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "697a71628807ec8bc63ce076d3bc8aba8a2cb3ccd82120a4f6e1d4807e56ea60"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.8+0/fts.v1.2.8.armv7l-linux-musleabihf.tar.gz"
[[fts]]
arch = "i686"
git-tree-sha1 = "78e8dc82420a72717cf055dbaddcba79bf7739ea"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "e7a8b0d46af7823d533a0078e76a6ef76cef02661056dd6dc124c97e7192394b"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.8+0/fts.v1.2.8.i686-linux-gnu.tar.gz"
[[fts]]
arch = "i686"
git-tree-sha1 = "289df563a76053deffed8c5e3edfa24ae335d609"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "5db6efc16328495ccd28fd8b93b364e6013f24c47cb0439cc2a31dbb213620e0"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.8+0/fts.v1.2.8.i686-linux-musl.tar.gz"
[[fts]]
arch = "powerpc64le"
git-tree-sha1 = "fa12c4466ef274b1ad41496f44a235d5663264c0"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "20c94c2539478977d7b55b2e2138ace8e1e1eabb392b9dff6043646cec33e82e"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.8+0/fts.v1.2.8.powerpc64le-linux-gnu.tar.gz"
[[fts]]
arch = "x86_64"
git-tree-sha1 = "83ad6455a24cc1b5e7607c72e49b0894d62ed47b"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "ace625e7db341bf7d47adc295b0d473b85a5a9bbdf80a2a4cacbf1256336765e"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.8+0/fts.v1.2.8.x86_64-linux-gnu.tar.gz"
[[fts]]
arch = "x86_64"
git-tree-sha1 = "58f0a4fff98aad89a9380f8700ff7365fd60eb35"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "c553972e6de08e381d250b42b8d608ab3e6704711fe72129ad337410b3ba56b1"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.8+0/fts.v1.2.8.x86_64-linux-musl.tar.gz"
