[[fts]]
arch = "aarch64"
git-tree-sha1 = "d33838315a7f9ca233270b317e14114a611795ba"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "affda9ce438487f127db9f64413b682fc668a52cc801d11ad8f7f3e1035adcf6"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.7+0/fts.v1.2.7.aarch64-linux-musl.tar.gz"
[[fts]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a28ccd9e6ffe0feca9e2d5f7ee680a26a7201f43"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "dd94278f9d2002b837831c6da507c5e666144d963bc322417128e07f7e3a6f19"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.7+0/fts.v1.2.7.armv7l-linux-musleabihf.tar.gz"
[[fts]]
arch = "i686"
git-tree-sha1 = "9e717abc6dce775c820401b74ff44ebd62c16aaf"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "3546b991969f62c45e7f273ec399d2a80330a879289fd6741d806f19dbe6d621"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.7+0/fts.v1.2.7.i686-linux-musl.tar.gz"
[[fts]]
arch = "x86_64"
git-tree-sha1 = "6622dacb697ab130c481e1d1935eebc1656b82ba"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "3d77d57448abc5e6f93b197efb6890ebb3ec8239581b700f1ea9230142e28201"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.7+0/fts.v1.2.7.x86_64-linux-musl.tar.gz"
