[[fts]]
arch = "aarch64"
git-tree-sha1 = "4d254badbec6df9a9a7cfad5f2ff1fa080c265cc"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "9f0fcb52ce28c33510553c7c895c64d293d6bebf75422ba9f2c9c3b6c5334dbd"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.aarch64-linux-gnu.tar.gz"
[[fts]]
arch = "aarch64"
git-tree-sha1 = "eb51ef67946a2afeae8b90c4523865d8c0ef4aa2"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "4dacb1252cede5fd2e091d4cfec7795bc8b905b369f6683399cbcd8e7f88b1dc"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.aarch64-linux-musl.tar.gz"
[[fts]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d0b684bd69f98c44eceee719a6632949471b745"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "9cb82b56abc00fc12cccc560b2e1e86cf2ecd05f36dc5aa530877110ee12f3ff"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.armv6l-linux-gnueabihf.tar.gz"
[[fts]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b9bbfbfc4dae348b8ab420da759df2f2fad0d354"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "4aecfaad5d2343e28ab9141624132c2b371180500d049c06b9fc5d4a31aef0d1"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.armv6l-linux-musleabihf.tar.gz"
[[fts]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56209a35b5c33e38e1f72d24ff2df50063a47f82"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "df54ae6398a5f969d7fb1693e235b6ccc339491263c5ae63bcaa5be432eed0d3"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.armv7l-linux-gnueabihf.tar.gz"
[[fts]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41367f6e857e6f50d9549f3a6f9e475f1b9cdcfa"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "2d28a788c19096fc3030c8478a29636c2bb5b189b49cc29aeebcfd7f9b9aeceb"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.armv7l-linux-musleabihf.tar.gz"
[[fts]]
arch = "i686"
git-tree-sha1 = "6802c08100fef62475eb3a842d018cf69452d587"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "c1c0c3e697c70d2e6ad54fd22569d81ef1708e108b73d0d72b7a9a05e13bbdd5"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.i686-linux-gnu.tar.gz"
[[fts]]
arch = "i686"
git-tree-sha1 = "9b1c42d96bee4fc06310b463b364d34cc4ea59b9"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "762d3c19e854aaab6a265d8a3e979713144c2e149b7478249a0f946d751cf591"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.i686-linux-musl.tar.gz"
[[fts]]
arch = "powerpc64le"
git-tree-sha1 = "2757fb4a1e876ba077c1c0b74f609b0d1b0051a0"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "de80658a7d2c031a60a9b044378f2dedec97012230f8595b76771075ebab5835"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.powerpc64le-linux-gnu.tar.gz"
[[fts]]
arch = "riscv64"
git-tree-sha1 = "b9269303474ef6997acbaab071e546b7e7ff72c0"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "db9f584b9d9027ecf772295b55b97b28047533ad5848a4089562d75b0fed1617"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.riscv64-linux-gnu.tar.gz"
[[fts]]
arch = "x86_64"
git-tree-sha1 = "154aa962730fb7ddac2455f0b1bf928b53d0061a"
libc = "glibc"
os = "linux"

    [[fts.download]]
    sha256 = "cd660dbdddbe3169d43ee202ac7db3e718679ac57c54c4e7c0eaf94030d0f94f"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.x86_64-linux-gnu.tar.gz"
[[fts]]
arch = "x86_64"
git-tree-sha1 = "3c785049cd940eee2d440cc8f462fa52b825953d"
libc = "musl"
os = "linux"

    [[fts.download]]
    sha256 = "866e726f256c172c7f388da77814164bfd39ab76403ffd4495128f338e8253ed"
    url = "https://github.com/JuliaBinaryWrappers/fts_jll.jl/releases/download/fts-v1.2.9+0/fts.v1.2.9.x86_64-linux-musl.tar.gz"
