# Autogenerated wrapper script for fts_jll for armv7l-linux-gnueabihf
export libfts

JLLWrappers.@generate_wrapper_header("fts")
JLLWrappers.@declare_library_product(libfts, "libfts.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfts,
        "lib/libfts.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
